#!/bin/bash
# the function "round()" was taken from
# http://stempell.com/2009/08/rechnen-in-bash/

#ffmpeg -i v.mp4 -i logo.png -i a.mp3 -filter_complex "[0:v]scale=720:-2,crop=min(500\,min(iw\,ih)):min(500\,min(iw\,ih))[bg];[bg][1:v] overlay=(W-w)/2:(H-h)/2" -pix_fmt yuv420p -map 2:a -shortest o.mp4
#ffmpeg -y -i 1.mpeg -i 2.mpeg -i 3.mpeg -i 4.mpeg -filter_complex '[0:v][1:v][2:v][3:v] concat=n=4:v=1 [v]' -map '[v]' -c:v libx264 -s 1280x720 -aspect 16:9 -q:v 1 -pix_fmt yuv420p o.mp4
#ffmpeg -i i.mp4 -i i.png -filter_complex "[1:v]format=rgba,fade=in:st=1:d=3:alpha=1,fade=out:st=6:d=3:alpha=1 [ovr]; [0][ovr] overlay" -codec:a copy O.mp4
#ffmpeg -y -loglevel warning -i 5sec_640x480.mp4 -i 5sec_1920x1080.mp4 -filter_complex " [0:v] scale=w=min(iw*480/ih\,640):h=min(480\,ih*640/iw), pad=w=640:h=480:x=(640-iw)/2:y=(480-ih)/2  [video0]; [1:v] scale=w=min(iw*480/ih\,640):h=min(480\,ih*640/iw), pad=w=640:h=480:x=(640-iw)/2:y=(480-ih)/2  [video1]; [0:a] anull [audio0]; [1:a] anull [audio1]; [video0][audio0][video1][audio1] concat=n=2:v=1:a=1 [v][a] " -map "[v]" -map "[a]" -c:a aac -c:v h264 -crf 18 -preset veryfast -f mp4 output.mp4
shopt -s extglob

# the round function:
round()
{
  echo $(printf %.$2f $(echo "scale=$2;(((10^$2)*$1)+0.5)/(10^$2)" | bc))
};
usage()
{
  echo "mvi [options...] merge audio with image"
  echo "-a audio file"
  echo "-i image file"
  echo "-c font color"
  echo "-s font size"
  echo "-b background color"
  echo "-l landscape"
  echo "-d duration"
  echo "-n number"
  echo "-t text"
  echo "usage: mvi"
  echo "mvi -a audio       change metadata"
  echo "mvi -a audio -n 2  break into 2 files"
  echo "mvi -i img%02d.jpg  images to video"
  echo "mvi -a audio%.mp3  merge audio"
  echo "mvi -a video%.mp4  merge video"
  echo "mvi -a audio -i image -c fontcolor"
  echo ""
  echo ""
  echo "input file format:"
  echo "file '001.jpg'"
  echo "duration 10"
  exit
}
if [ $# -lt 1 ]; then
  usage
fi

while getopts t:n:r:a:d:i:c:s:b:ol option
do
case "${option}"
in
a) audio=${OPTARG};;
i) image=${OPTARG};;
c) color=${OPTARG};;
s) fontsize=${OPTARG};;
b) bgcolor=${OPTARG};;
r) rate=${OPTARG};;
t) text=${OPTARG};;
n) number=${OPTARG};;
d) duration=${OPTARG};;
o) only="true";;
l) landscape="true";;
esac
done


FONT_FILE="/Library/Fonts/Arial Unicode.ttf"
if [ -z "$audio" ]; then
  file=$(basename "$image")
else
  file=$(basename "$audio")
fi
title=${file%.*}
if [ -z "$image" ]; then
  if [[ "$audio" == *"%"* ]]; then
    audio=${audio//%/*}
    files=($audio)
    echo ${#files[@]}
    f=${files[1]}
    ext="${f##*.}"
    ffmpeg -safe 0 -f concat -i <(for f in $audio; do echo "file '$PWD/$f'"; done) -c copy merged.$ext
    exit
  fi

  if [ ! -z "$text" ]; then
    ffmpeg -v error -i "$audio" -vf "drawtext=text='${text}':fontfile=${FONT_FILE}:fontsize=${fontsize}:fontcolor=${color}@1:x=(w-text_w)/2:y=h-th-1:box=1:boxcolor=black@0.8:boxborderw=0,$scale" "$title-text.mp4"
    exit
  fi
  # split
  if [ -z "$number" ]; then
    DESC=$(date +%s)
    ffmpeg -i "$audio" -metadata --title="$title" -metadata --description="$DESC" -c copy "$DESC-$audio"
  else
    duration=$(ffprobe -i "$audio" -show_entries format=duration -v quiet -of csv="p=0")
    duration=${duration%.*}
    duration=$(((duration+number-1)/number+1))
    ext="${audio##*.}"
    ffmpeg -i "$audio" -f segment -segment_time $duration -codec copy -reset_timestamps 1 -segment_start_number 1 "$title-%02d.$ext"
  fi
  exit
fi

#default rate when no change for image
rate=${rate:-1/5}

if [ -z "$duration" ]; then
  duration=$(ffprobe -i "$audio" -show_entries format=duration -v quiet -of csv="p=0")
fi
bitrate=$(ffprobe -i "$audio" -show_entries format=bit_rate -v quiet -of csv="p=0")

if [[ "$image" == *".txt"* ]]; then
  width=640
  height=480
  scale="scale=w=$width:h=$height:force_original_aspect_ratio=1,pad=$width:$height:(ow-iw)/2:(oh-ih)/2"
  ffmpeg -v error -f concat -safe 0 -i "$image" -i "$audio" -c:v libx264 -c:a aac -pix_fmt yuv420p -vf "$scale" -crf 28 -r $rate -t $duration -shortest -y "$title.mp4"
  exit
elif [[ "$image" == *".csv"* ]]; then
  i=1
  while IFS=, read -r ts file text
  do
     test $i -eq 1 && ((i=i+1)) && continue
    echo "timestamp : $ts"
    echo "file : $file"
    echo "text : $text"
  done < $image
  exit
fi

eval $(ffprobe -v error -select_streams v:0 -show_entries stream=width,height -of default=noprint_wrappers=1 $image)
#ffmpeg -i a.jpg -vf scale=640:480 b.jpg
#Padded dimensions cannot be smaller than input dimensions.
chars=$(echo -n $title|wc -m|grep -oE "[0-9]+")
echo "image width=${width} height=${height}"

audio_option="-acodec copy"
#audio_option="-c:a aac -b:a $bitrate"
audio_option="-c:a aac -b:a $bitrate"
#ffmpeg -r 60 -f image2 -s 1280x720 -i pic%05d.png -i MP3FILE.mp3 -vcodec libx264 -b 4M -vpre normal -acodec copy OUTPUT.mp4 
bgcolor=${bgcolor:-black}
if [ -z "$color" ]; then
  color="white"
fi

MIN_FONT_SIZE=14
GAP=20
fontsize=$(round "($width-$GAP)/$chars" 0)
echo "fontsize=$fontsize"

if [ -z "$audio" ]; then
  convert -font "$FONT_FILE" -pointsize 14 $image -fill white -undercolor '#00000080' -gravity South -annotate +0+5 "$title" "anno_$title.jpg"
  exit
fi

#2160p: 3840x2160 1440p: 2560x1440 1080p: 1920x1080 720p: 1280x720
#480p: 854x480 360p: 640x360 240p: 426x240
#https://stackoverflow.com/questions/30789367/ffmpeg-how-to-convert-vertical-video-with-black-sides-to-video-169-with-blur
land=""
if [ ! -z "$landscape" ]; then
  land=",split[original][copy];[copy]scale=ih*16/9:-1,crop=h=iw*9/16,gblur=sigma=20[blurred];[blurred][original]overlay=(main_w-overlay_w)/2:(main_h-overlay_h)/2"
fi

scale="pad=width=ceil(iw/2)*2:height=ceil(ih/2)*2"
if [[ "$image" == *"%"* ]]; then
  h=$(round $width/16*9 0)
  if (($h < $height )); then
    width=$(round $height/9*16 0)
  fi
  scale="scale=w=$width:h=$height:force_original_aspect_ratio=1,pad=$width:$height:(ow-iw)/2:(oh-ih)/2"
fi

image_option=" -r $rate -f image2 -loop 1 "
if [[ "$image" == *".gif"* ]]; then
  $rate=$(ffprobe -v error -select_streams v:0 -show_entries stream=avg_frame_rate -of default=noprint_wrappers=1:nokey=1)
  image_option="-r $rate -ignore_loop 0"
fi

text="${title//%/\\\\\\\\%}"
#drawtext=enable='between(t,12,3*60)'
if [ ! -z "$only" ]; then
  ffmpeg -v error $image_option -i "$image" -i "$audio" -c:v libx264 -tune stillimage $audio_option -pix_fmt yuv420p -vf "$scale$land" -crf 28 -t $duration -shortest "$title.mp4"
else
  # enough space to show text
  if [ "$fontsize" -ge "$MIN_FONT_SIZE" ]; then
    ffmpeg -v error $image_option -i "$image" -i "$audio" -c:v libx264 -tune stillimage $audio_option -pix_fmt yuv420p -t $duration -shortest -vf "drawtext=text='${text}':fontfile=$FONT_FILE:fontsize=${fontsize}:fontcolor=${color}@1:x=(w-text_w)/2:y=h-th-1:box=1:boxcolor=black@0.8:boxborderw=0,$scale" "$title.mp4"
  else
    #crop=floor(iw/2)*2:floor(ih/2)*2 
    fontsize=MIN_FONT_SIZE
    rate=1
    ffmpeg -v error $image_option -i "$image" -i "$audio" -c:v libx264 -tune stillimage $audio_option -pix_fmt yuv420p -t $duration -shortest -vf "$scale,drawtext=text='${text}':fontfile=$FONT_FILE:fontsize=40:fontcolor=white@1:x=w-mod(50*t\, (w+text_w)):y=h-th-1:box=1:boxcolor=black@0.8" "$title.mp4"
  fi
fi
